
//Login/Register/Auth
export const REGISTER_FORM = 'REGISTER_FORM';
export const REGISTER_FORM_CLEANUP = 'REGISTER_FORM_CLEANUP';
export const LOGIN_FORM = 'LOGIN_FORM';
export const LOGIN_FORM_CLEANUP = 'LOGIN_FORM_CLEANUP';
export const POST_LOGIN = 'POST_LOGIN';
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CONTAINER_TOGGLE = 'CONTAINER_TOGGLE';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH_TIME = 'CHECK_AUTH_TIME';


//Navbar
export const TOGGLE_NAV = 'TOGGLE_NAV';

//Projects
export const FETCH_ALL_PROJECTS = 'FETCH_ALL_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const PROJECT_CLEANUP = 'PROJECT_CLEANUP';
export const POST_PROJECT_FORM = 'POST_PROJECT_FORM';
export const PROJECT_FORM_CLEANUP = 'PROJECT_FORM_CLEANUP';
export const CHANGE_PROJECT_FORM = 'CHANGE_PROJECT_FORM';
export const TOGGLE_COMPLETED_PROJECTS = 'TOGGLE_COMPLETED_PROJECTS';

//Blocks
export const FETCH_ALL_BLOCKS = 'FETCH_ALL_BLOCKS';
export const FETCH_BLOCK = 'FETCH_BLOCK';
export const TOGGLE_NEW_BLOCK = 'TOGGLE_NEW_BLOCK';
export const BLOCK_CLEANUP = 'BLOCK_CLEANUP';
export const POST_BLOCK_FORM = 'POST_BLOCK_FORM';
export const BLOCK_FORM_CLEANUP = 'BLOCK_FORM_CLEANUP';
export const CHANGE_BLOCK_FORM = 'CHANGE_BLOCK_FORM';
export const FETCH_DELETE_BLOCK = 'FETCH_DELETE_BLOCK';


//Tasks
export const FETCH_TASK = 'FETCH_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TOGGLE_TASK_COSTS = 'TOGGLE_TASK_COSTS';
export const CHANGE_TASK_BUDGET = 'CHANGE_TASK_BUDGET';
export const SUBMIT_TASK_BUDGET = 'SUBMIT_TASK_BUDGET';
export const POST_TASK_FORM = 'POST_TASK_FORM';
export const CHANGE_TASK_FORM = 'CHANGE_TASK_FORM';
export const TASK_FORM_CLEANUP = 'TASK_FORM_CLEANUP';
export const TOGGLE_TASK_FORM = 'TOGGLE_TASK_FORM';
export const FETCH_START_TASK = 'FETCH_START_TASK';
export const FETCH_COMPLETE_TASK = 'FETCH_COMPLETE_TASK';

//Task Budgeting

export const ADD_TASK = 'ADD_TASK';

//Budget
export const FETCH_BUDGET = 'FETCH_BUDGET';

//Cost
export const POST_COST_FORM = 'POST_COST_FORM';
export const CHANGE_COST_FORM = 'CHANGE_COST_FORM';
export const COST_FORM_CLEANUP = 'COST_FORM_CLEANUP';
export const POST_LABOR_COST = 'POST_LABOR_COST';
export const POST_SM_COST = 'POST_SM_COST';

//Performance
export const FETCH_PROJECT_PERF = 'FETCH_PROJECT_PERF';
export const FETCH_GENERAL_PERF = 'FETCH_GENERAL_PERF';
export const FETCH_ALL_PROJECT_INDICATORS = 'FETCH_ALL_PROJECT_INDICATORS';
export const GET_INDICATORS = 'GET_INDICATORS';
